# Generated by Django 5.2.4 on 2025-07-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sexo',
            field=models.IntegerField(blank=True, choices=[(0, 'Não informar'), (1, 'Feminino'), (2, 'Masculino')], null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='url_site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
