# Generated by Django 5.2.4 on 2025-07-15 15:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_pessoa', models.IntegerField(choices=[(1, 'Física'), (2, 'Jurídica')])),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('endereco_completo', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fotoflow.tipocliente')),
            ],
        ),
    ]
