# Generated by Django 5.1 on 2025-09-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.IntegerField(choices=[(1, 'Pessoa Física'), (2, 'Pessoa Jurídica')], verbose_name='Tipo do cliente')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF/CNPJ')),
                ('rg_ie', models.CharField(blank=True, max_length=50, null=True, verbose_name='RG/IE')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='Telefone(s)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('endereco_completo', models.CharField(max_length=200, verbose_name='Endereço completo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'ordering': ['nome_completo'],
            },
        ),
    ]
