# Generated by Django 5.2.4 on 2025-07-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_cliente',
        ),
    ]
