# Generated by Django 5.1 on 2025-09-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.IntegerField(choices=[(1, 'Noiva'), (2, 'Noivo')], null=True, verbose_name='Tipo do cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.IntegerField(choices=[(1, 'Pessoa Física'), (2, 'Pessoa Jurídica')], verbose_name='PF/PJ'),
        ),
    ]
