# Generated by Django 5.2.4 on 2025-07-15 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0002_remove_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fotoflow.tipocliente'),
        ),
    ]
