# Generated by Django 5.1 on 2025-09-12 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0002_cliente_tipo_cliente_alter_cliente_tipo_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='modelos_contrato/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='fotoflow.modelocontrato')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('noivo', 'Noivo'), ('noiva', 'Noiva'), ('responsavel', 'Responsável Financeiro'), ('testemunha', 'Testemunha')], max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_participados', to='fotoflow.cliente')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participantes', to='fotoflow.contrato')),
            ],
            options={
                'unique_together': {('contrato', 'cliente', 'papel')},
            },
        ),
    ]
