# Generated by Django 5.2.4 on 2025-07-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0003_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocliente',
            name='tipo_pessoa',
            field=models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default='1'),
        ),
    ]
