# Generated by Django 5.1 on 2025-09-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0003_modelocontrato_contrato_contratocliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco_completo',
            field=models.CharField(max_length=255, verbose_name='Endereço completo'),
        ),
    ]
