# Generated by Django 5.2.4 on 2025-07-16 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0004_tipocliente_tipo_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_cadastro',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tipocliente',
            old_name='tipo_pessoa',
            new_name='situacao',
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tipocliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
