# Generated by Django 5.1 on 2025-09-12 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0005_contrato_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Serviço',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='contratocliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-09-12 16:00:34.909611', verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratocliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.CreateModel(
            name='ContratoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='fotoflow.contrato')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_servicos', to='fotoflow.servico')),
            ],
            options={
                'unique_together': {('contrato', 'servico')},
            },
        ),
    ]
