# Generated by Django 5.2.4 on 2025-07-16 00:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0005_rename_data_cadastro_cliente_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocliente',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
