# Generated by Django 5.1 on 2025-09-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0006_servico_contratocliente_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='detalhes',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Detalhes'),
        ),
    ]
