# Generated by Django 5.2.4 on 2025-07-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0006_alter_tipocliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.IntegerField(choices=[(1, 'Física'), (2, 'Jurídica')], default='1'),
        ),
    ]
