# Generated by Django 5.1 on 2025-09-12 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0007_servico_detalhes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoservico',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='fotoflow.contrato'),
        ),
    ]
