# Generated by Django 5.2.4 on 2025-07-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0007_alter_cliente_tipo_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='chave_acesso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha_acesso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
