# Generated by Django 5.2.4 on 2025-07-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0008_cliente_chave_acesso_cliente_senha_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='situacao',
            field=models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default='1'),
        ),
    ]
