# Generated by Django 5.2.4 on 2025-07-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0009_cliente_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
