# Generated by Django 5.2.4 on 2025-09-15 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0009_cliente_usuario_contrato_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='fotoflow.modelocontrato'),
        ),
        migrations.AlterField(
            model_name='contratocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_participados', to='fotoflow.cliente'),
        ),
        migrations.AlterField(
            model_name='contratocliente',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='fotoflow.contrato'),
        ),
        migrations.AlterField(
            model_name='contratoservico',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='fotoflow.contrato'),
        ),
        migrations.AlterField(
            model_name='contratoservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_servicos', to='fotoflow.servico'),
        ),
    ]
