# Generated by Django 5.2.4 on 2025-09-15 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0011_alter_contrato_modelo_alter_contratocliente_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='fotoflow.modelocontrato'),
        ),
    ]
