# Generated by Django 5.2.4 on 2025-09-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0012_alter_contrato_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocontrato',
            name='arquivo',
            field=models.FileField(upload_to='files/modelos_contrato/'),
        ),
    ]
