# Generated by Django 5.2.4 on 2025-09-15 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0013_alter_modelocontrato_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocliente',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_participados', to='fotoflow.cliente'),
        ),
        migrations.AlterField(
            model_name='contratocliente',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes', to='fotoflow.contrato'),
        ),
        migrations.AlterField(
            model_name='contratoservico',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='fotoflow.contrato'),
        ),
        migrations.AlterField(
            model_name='contratoservico',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_servicos', to='fotoflow.servico'),
        ),
    ]
