# Generated by Django 5.2.4 on 2025-07-17 15:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0013_tokenpublico'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTrabalho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
