# Generated by Django 5.2.4 on 2025-09-15 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0014_alter_contratocliente_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocliente',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_participados', to='fotoflow.cliente'),
            preserve_default=False,
        ),
    ]
