# Generated by Django 5.2.4 on 2025-09-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0015_alter_contratocliente_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_pessoa',
        ),
    ]
