# Generated by Django 5.2.4 on 2025-07-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0015_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
