# Generated by Django 5.2.4 on 2025-09-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0016_remove_cliente_tipo_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(max_length=50, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco_completo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço completo'),
        ),
    ]
