# Generated by Django 5.2.4 on 2025-07-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0017_tipotrabalho_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotrabalho',
            name='situacao',
            field=models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default='1'),
        ),
    ]
