# Generated by Django 5.2.4 on 2025-07-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoflow', '0018_tipotrabalho_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotrabalho',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipotrabalho',
            name='nome_controle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tipotrabalho',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
